homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 45
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.yr_temperature:
      friendly_name: Temperatur

    sensor.yr_humidity:
      friendly_name: Luftfuktighet
      icon: mdi:water-percent

    sensor.yr_wind_Speed:
      friendly_name: Vind
      icon: mdi:weather-windy

    sensor.yr_cloudiness:
      friendly_name: 'Molntäcke'
      icon: mdi:cloud
      

    media_player.ue46d6300_ue46d6300:
      friendly_name: SamsungTV

    sensor.mqtt_sensor:
      friendly_name: "Broker Uptime"
      icon: mdi:clock
      
    sensor.183_temperature:
      friendly_name: "Temperatur"
      
    sensor.183_humidity:
      friendly_name: "Luftfuktighet"
      icon: mdi:water-percent

    sensor.151_temperature:
      friendly_name: Kylskåp

    sensor.167_temperature:
      friendly_name: Frys

    sensor.199_temperature:
      friendly_name: Temperatur

    switch.vardagsrumleft:
      hidden: true
    
    switch.vardagsrumright:
      hidden: true

    switch.sovrum:
      hidden: true

    switch.hall:
      hidden: true

    switch.kok:
      hidden: true

    switch.elvis:
      hidden: true
      
    switch.ute:
      hidden: true
      
    switch.round_one:
      hidden: true
      
    switch.round_three:
      hidden: true

    light.livingroom_lights:
      friendly_name: Vardagsrum

    light.master_bedroom:
      friendly_name: Sovrum

    light.elvis_bedroom:
      friendly_name: "Elvis rum"

    light.hallway_light:
      friendly_name: Hall

    light.kitchen_light:
      friendly_name: "Kök"
      
    light.outback_light:
      friendly_name: "Slinga ute"
      
    light.outfront_light:
      friendly_name: "Slinga fram"
      
    light.upstairs_hallway_light:
      friendly_name: "Hall upp"

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enable the editor panel
panel_iframe:
  editor:
    title: 'Editor'
    url: 'http://10.0.0.33:3000'
    icon: mdi:book-open

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


#Presence detection
device_tracker:
  - platform: asuswrt
    host: 10.0.0.254
    username: admin
    password: !secret asus_password

#IKEA Trådfri
#tradfri:


mqtt:
  broker: rpi.pyth.se
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1 

# Sensors
sensor:

  - platform: yr
    monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature
  
  - platform: mqtt
    state_topic: "chatt/#"
    
  - platform: tellstick

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /

 # - platform: template
 #   sensors:
 #     kitchen_move:
 #       value_template: '{% if is_state("switch.move1", "on") %}movement{% else %}still{% endif %}'
 #       friendly_name: 'Kitchen movement'

binary_sensor: 
  - platform: template 
    sensors:
      movement_kitchen:
        friendly_name: "Rörelse kök"
        value_template: "{{ states.switch.move1.state == 'on' }}"
        device_class: motion

      movement_hallway:
        friendly_name: "Rörelse Hall"
        value_template: "{{ states.switch.move2.state == 'on' }}"
        device_class: motion        

light:
  - platform: template
    lights:
      livingroom_lights:
        friendly_name: "Vardagsrum"
        turn_on:
          service: switch.turn_on
          entity_id: switch.vardagsrumleft, switch.vardagsrumright
        turn_off:
          service: switch.turn_off
          entity_id: switch.vardagsrumleft, switch.vardagsrumright
        set_level:
          service: switch.turn_off
          entity_id: switch.vardagsrumleft, switch.vardagsrumright
      
      master_bedroom:
        friendly_name: "Sovrum"
        turn_on:
          service: switch.turn_on
          entity_id: switch.sovrum
        turn_off:
          service: switch.turn_off
          entity_id: switch.sovrum
        set_level:
          service: switch.turn_off
          entity_id: switch.sovrum

      elvis_bedroom:
        friendly_name: "Elvis rum"
        turn_on:
          service: switch.turn_on
          entity_id: switch.elvis
        turn_off:
          service: switch.turn_off
          entity_id: switch.elvis
        set_level:
          service: switch.turn_off
          entity_id: switch.elvis  

      hallway_light:
        friendly_name: "Hall"
        turn_on:
          service: switch.turn_on
          entity_id: switch.hall
        turn_off:
          service: switch.turn_off
          entity_id: switch.hall
        set_level:
          service: switch.turn_off
          entity_id: switch.hall 

      kitchen_light:
        friendly_name: "Kök"
        turn_on:
          service: switch.turn_on
          entity_id: switch.kok
        turn_off:
          service: switch.turn_off
          entity_id: switch.kok
        set_level:
          service: switch.turn_off
          entity_id: switch.kok

      outback_light:
        friendly_name: "Ute slinga"
        turn_on:
          service: switch.turn_on
          entity_id: switch.ute
        turn_off:
          service: switch.turn_off
          entity_id: switch.ute
        set_level:
          service: switch.turn_off
          entity_id: switch.ute

      outfront_light:
        friendly_name: "Ute slinga framsida"
        turn_on:
          service: switch.turn_on
          entity_id: switch.round_three
        turn_off:
          service: switch.turn_off
          entity_id: switch.round_three
        set_level:
          service: switch.turn_off
          entity_id: switch.round_three

      upstairs_hallway_light:
        friendly_name: "Hall uppe"
        turn_on:
          service: switch.turn_on
          entity_id: switch.round_one
        turn_off:
          service: switch.turn_off
          entity_id: switch.round_one
        set_level:
          service: switch.turn_off
          entity_id: switch.round_one



# Cameras
camera:
  - platform: generic
    still_image_url: https://orion.trafikverket.se/CameraImages/share/wcm/537.jpg
    name: Överjärva

  - platform: generic
    still_image_url: https://orion.trafikverket.se/CameraImages/share/wcm/541.jpg
    name: JärvaKrog

  - platform: generic
    still_image_url: https://orion.trafikverket.se/CameraImages/share/wcm/546.jpg
    name: Haga Norra

  - platform: generic
    still_image_url: https://orion.trafikverket.se/CameraImages/share/wcm/528.jpg
    name: Vårby
    
  - platform: mjpeg
    mjpeg_url: http://10.0.0.134:9999/videostream.cgi?user=admin&pwd=9pfzrxmj8wm
    name: Home

lock:
  platform: mqtt
  name: Frontdoor 
  state_topic: "home-assistant/frontdoor/"
  command_topic: "home-assistant/frontdoor/set"
  payload_lock: "LOCK"
  payload_unlock: "UNLOCK"
  optimistic: false
  qos: 1
  retain: true
  value_template: '{{ value.x }}' 


# Text to speech
tts:
  platform: google
  language: 'sv'


#Tellstick
tellstick:
  signal_repetitions: 6


input_boolean:
  auto_light_mode:
    name: Automatiska lampor
    initial: off
    icon: mdi:lightbulb-outline

switch:
  - platform: tellstick

  - platform: template
    switches:
      panel1_left_template:
        value_template: "{{ is_state('switch.panel1Left', 'on') }}"
        turn_on:
          service: light.turn_on
          entity_id: group.down_stairs 
        turn_off:
          service: light.turn_off
          entity_id: group.down_stairs

      panel1_right_template:
        value_template: "{{ is_state('switch.panel1Right', 'on') }}"
        turn_on:
          service: light.turn_on
          entity_id: light.outback_light
        turn_off:
          service: light.turn_off
          entity_id: light.outback_light            


panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

notify:
  - name: homectl_slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#general'
    username: homeassistant

media_player spotify:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

#Automations
automation: !include automations.yaml

#Groups
group: !include groups.yaml